name: توليد الوثائق

on:
  release:
    types: [released]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: الفحص
        uses: actions/checkout@v4

      - name: إعداد Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: https://registry.npmjs.org

      - name: تثبيت التبعيات
        run: npm ci --ignore-scripts

      - name: توليد الوثائق
        run: npm run docs

      - name: إعداد الصفحات
        uses: actions/configure-pages@v4

      - name: رفع الملف
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: النشر على صفحات جيتهاب
        id: deployment
        uses: actions/deploy-pages@v4
